apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce  # or ReadWriteMany, ReadOnlyMany based on your requirements
  resources:
    requests:
      storage: 1Gi  # Specify the amount of storage you need
